import {BaseScene} from './BaseScene';
import {bus} from '../../core/EventBus';
import Phaser from 'phaser';
const P=Phaser;
export class EndingScene extends BaseScene{
  branch:''|'A'|'B'|'C'=''; stitches=0; removed=0; shutter:any; lamp:any;
  constructor(){super('Ending')}
  preload(){this.loadSceneImage('mask-shop.webp')}
  create(){const w=this.scale.width,h=this.scale.height;this.add.image(w/2,h/2,'bg').setDisplaySize(w,h).setTint(0xb8ab94);this.add.rectangle(w/2,h/2,w,h,0x0b0c0a,.34);bus.emit('hint','结局不再问“你选什么”。场景里有三件可以真正动手做的事：镜前半张脸、脸上的缝线、墙上的面具与门板。第一个不可逆动作会成为你的选择。');
    this.acceptArea(w,h);this.facelessArea(w,h);this.closeArea(w,h);
  }
  commit(b:'A'|'B'|'C'){if(this.branch&&this.branch!==b)return false;if(!this.branch){this.branch=b;this.feedback(`你没有点击“${b}”。你只是开始做一件不能假装没做过的事。`,true)}return true}
  acceptArea(w:number,h:number){const mirror=this.add.rectangle(w*.2,h*.42,w*.24,h*.48,0x1a1c1b,.48).setStrokeStyle(2,0xb9a781,.72);this.add.text(w*.2,h*.16,'旧镜',{fontFamily:'serif',fontSize:'16px',color:'#d8c8aa'}).setOrigin(.5);const half=this.add.container(w*.2,h*.76);half.add([this.add.rectangle(0,0,w*.12,h*.12,0xcdbb9a,.84).setStrokeStyle(1,0x49392b),this.add.text(0,0,'师父留下的\n半张脸',{fontFamily:'serif',fontSize:'11px',color:'#211b15',align:'center'}).setOrigin(.5)]);half.setSize(w*.12,h*.12).setInteractive({draggable:true});this.input.setDraggable(half);half.on('drag',(_:any,x:number,y:number)=>{if(this.branch&&this.branch!=='A')return;half.x=x;half.y=y});half.on('dragend',()=>{if(P.Geom.Intersects.RectangleToRectangle(half.getBounds(),mirror.getBounds())&&half.x>mirror.x){if(!this.commit('A')){half.x=w*.2;half.y=h*.76;return}half.disableInteractive();half.x=mirror.x+mirror.width*.18;half.y=mirror.y;this.feedback('右半脸被贴合；左半仍保持空白。完整不是对称，而是允许缺失继续存在。',true);this.finish('A')}else{half.x=w*.2;half.y=h*.76;this.feedback('镜子没有接受这个位置。师父留下的是右半，不是替阿七补齐整张脸。')}})}
  facelessArea(w:number,h:number){const face=this.add.rectangle(w*.5,h*.42,w*.22,h*.38,0xd1c2a5,.36).setStrokeStyle(1,0xc8b58e,.65);this.add.text(w*.5,h*.16,'被残响固定的脸',{fontFamily:'serif',fontSize:'16px',color:'#d8c8aa'}).setOrigin(.5);for(let i=0;i<5;i++){const y=h*(.3+i*.065);const stitch=this.add.container(w*.5,y);stitch.add([this.add.rectangle(0,0,w*.18,4,0x32291f,.95),this.add.circle(-w*.09,0,4,0xb29c76),this.add.circle(w*.09,0,4,0xb29c76)]);stitch.setSize(w*.2,22).setInteractive({draggable:true});this.input.setDraggable(stitch);const sx=stitch.x;stitch.on('drag',(_:any,x:number)=>{if(this.branch&&this.branch!=='B')return;stitch.x=P.Math.Clamp(x,sx-120,sx+120)});stitch.on('dragend',()=>{if(Math.abs(stitch.x-sx)>70){if(!this.commit('B')){stitch.x=sx;return}stitch.destroy();this.stitches++;this.feedback(`第 ${this.stitches} 根缝线被拉掉。脸开始失去单一形状。`,true);if(this.stitches===5)this.finish('B')}else{stitch.x=sx;this.feedback('线被扯紧又弹回去。要真正把固定它的线拉掉。')}})} }
  closeArea(w:number,h:number){this.add.text(w*.82,h*.16,'面具墙与门板',{fontFamily:'serif',fontSize:'16px',color:'#d8c8aa'}).setOrigin(.5);const masks=[];for(let i=0;i<5;i++){const x=w*(.75+(i%2)*.13),y=h*(.28+Math.floor(i/2)*.13);const m=this.add.container(x,y);m.add([this.add.rectangle(0,0,w*.09,h*.09,0x6f604d,.86).setStrokeStyle(1,0xb69f79),this.add.text(0,0,String(i+1),{fontFamily:'serif',fontSize:'12px',color:'#eadfc9'}).setOrigin(.5)]);m.setSize(w*.09,h*.09).setInteractive({draggable:true});this.input.setDraggable(m);const hx=x,hy=y;m.on('drag',(_:any,nx:number,ny:number)=>{if(this.branch&&this.branch!=='C')return;m.x=nx;m.y=ny});m.on('dragend',()=>{if(m.y>h*.72){if(!this.commit('C')){m.x=hx;m.y=hy;return}m.destroy();this.removed++;this.feedback(`第 ${this.removed} 张面具被摘下，没有替任何人归回原位。`,true);if(this.removed===5)this.enableShutter(w,h)}else{m.x=hx;m.y=hy}});masks.push(m)} }
  enableShutter(w:number,h:number){this.shutter=this.add.rectangle(w*.82,h*.52,w*.28,h*.09,0x493a2a,.94).setStrokeStyle(2,0x1d160f).setInteractive({draggable:true});this.add.text(w*.82,h*.52,'木门板',{fontFamily:'serif',fontSize:'14px',color:'#e8dac0'}).setOrigin(.5);this.input.setDraggable(this.shutter);const sy=this.shutter.y;this.shutter.on('drag',(_:any,_x:number,y:number)=>{this.shutter.y=P.Math.Clamp(y,sy,sy+140)});this.shutter.on('dragend',()=>{if(this.shutter.y-sy>90){this.feedback('门板被拉下。现在只剩工作灯还亮着。',true);this.enableLamp(w,h)}else this.shutter.y=sy})}
  enableLamp(w:number,h:number){this.lamp=this.add.text(w*.82,h*.82,'吹灭工作灯',{fontFamily:'serif',fontSize:'16px',color:'#f0ddb5',backgroundColor:'#493c2bdd',padding:{x:12,y:8}}).setOrigin(.5).setInteractive();this.lamp.on('pointerdown',()=>{this.cameras.main.fadeOut(this.state.reduced?0:900,0,0,0);this.time.delayedCall(this.state.reduced?50:950,()=>this.finish('C'))})}
  finish(b:'A'|'B'|'C'){if(this.state.ending)return;this.state.ending=b;this.state.endingFlags.push(`ending_${b}`);this.store.save();this.time.delayedCall(700,()=>bus.emit('endingComplete',b))}
}
