import {BaseScene} from './BaseScene';
import {bus} from '../../core/EventBus';
import {audio} from '../../core/AudioManager';
import Phaser from 'phaser';
const P=Phaser;
export class WaterMemoryScene extends BaseScene{
  progress=0;fogProgress=0;hand:any;fog:any;fogRT:any;dragging=false;lastAngle=0;completed=false;
  constructor(){super('Water')}
  preload(){this.loadSceneImage('water-memory.webp')}
  create(){const w=this.scale.width,h=this.scale.height;this.add.image(w/2,h/2,'bg').setDisplaySize(w,h).setTint(0x93a3a1);bus.emit('hint','房间里所有东西都在倒流，只有墙钟顺时针。抓住分针，逆时针拖动；第三声后用手擦开镜雾。');
    const clock=this.add.container(w*.74,h*.32).setDepth(5);clock.add(this.add.circle(0,0,Math.min(w,h)*.12,0x171816,.68).setStrokeStyle(3,0xd0b98b));for(let i=0;i<12;i++){const a=P.Math.DegToRad(i*30-90),r=Math.min(w,h)*.1;clock.add(this.add.circle(Math.cos(a)*r,Math.sin(a)*r,2.2,0xd9c7a5,.85))}this.hand=this.add.rectangle(0,-Math.min(w,h)*.065,3,Math.min(w,h)*.13,0xe0cfaa,.94).setOrigin(.5,1);clock.add(this.hand);clock.setSize(Math.min(w,h)*.28,Math.min(w,h)*.28).setInteractive(new P.Geom.Circle(0,0,Math.min(w,h)*.14),P.Geom.Circle.Contains);clock.on('pointerdown',(p:any)=>{this.dragging=true;this.lastAngle=P.Math.RadToDeg(P.Math.Angle.Between(clock.x,clock.y,p.x,p.y))});this.input.on('pointerup',()=>this.dragging=false);this.input.on('pointermove',(p:any)=>{if(!this.dragging||this.completed)return;const a=P.Math.RadToDeg(P.Math.Angle.Between(clock.x,clock.y,p.x,p.y));let d=P.Math.Angle.WrapDegrees(a-this.lastAngle);this.lastAngle=a;if(d<0){this.progress=P.Math.Clamp(this.progress+Math.abs(d)/3.2,0,100);this.hand.angle=-this.progress*4.2;this.updateWorld()}else if(d>5)this.feedback('顺时针只是让墙钟继续服从原来的时间。')});
    this.add.text(w*.5,h*.82,'水滴 ↑   烛泪 ↑   碎玻璃 ←   床单褶皱 ↶',{fontFamily:'serif',fontSize:'15px',color:'#d7ddd7',backgroundColor:'#10141199',padding:{x:12,y:7}}).setOrigin(.5).setAlpha(.78);
    this.events.once('shutdown',()=>this.input.removeAllListeners());
    if(this.state.prologue.water){this.completed=true;this.add.text(w*.5,h*.5,'第三声钟已经过去。\n镜上只剩“不要替他——”。',{fontFamily:'serif',fontSize:'22px',align:'center',color:'#e4dccb',backgroundColor:'#141512bb',padding:{x:20,y:14}}).setOrigin(.5);this.makeZone(w*.1,h*.1,w*.12,h*.08,'返回面具铺',()=>bus.emit('scene','shop'))}
  }
  updateWorld(){const cam=this.cameras.main;const p=this.progress;cam.setZoom(1+(p/100)*.015);cam.setAlpha(.96+.04*(p/100));if(p>25&&!(this as any).one){(this as any).one=1;audio.sfx('clock');this.feedback('第一声：床单褶皱消失，碎玻璃向镜框移动。',true)}if(p>50&&!(this as any).two){(this as any).two=1;audio.sfx('clock');this.feedback('第二声：水线从墙脚退回天花板。',true)}if(p>=83&&!this.fog){audio.sfx('clock');this.spawnFog()}}
  spawnFog(){const w=this.scale.width,h=this.scale.height;this.fog=this.add.container(0,0).setDepth(30);this.fog.add(this.add.rectangle(w/2,h/2,w,h,0x101513,.35));const mx=w*.52,my=h*.46,mw=w*.48,mh=h*.5;const rt=this.add.renderTexture(mx-mw/2,my-mh/2,mw,mh).setOrigin(0);this.fogRT=rt;const g=this.make.graphics({x:0,y:0}, false);g.fillStyle(0xd8d4c8,.92);g.fillRect(0,0,mw,mh);for(let i=0;i<80;i++){g.fillStyle(0xbec8c5,P.Math.FloatBetween(.04,.16));g.fillCircle(P.Math.Between(0,mw),P.Math.Between(0,mh),P.Math.Between(8,36))}rt.draw(g);this.fog.add(rt);this.fog.add(this.add.text(mx,my-mh/2-28,'第三声。镜子起雾了。',{fontFamily:'serif',fontSize:'18px',color:'#eee5d5'}).setOrigin(.5));const brush=this.make.graphics({x:0,y:0}, false);brush.fillStyle(0xffffff,1);brush.fillCircle(0,0,26);rt.setInteractive(new P.Geom.Rectangle(0,0,mw,mh),P.Geom.Rectangle.Contains);let wiping=false;rt.on('pointerdown',()=>wiping=true);this.input.on('pointerup',()=>wiping=false);this.input.on('pointermove',(p:any)=>{if(!wiping||this.completed)return;const x=p.x-(mx-mw/2),y=p.y-(my-mh/2);if(x<0||y<0||x>mw||y>mh)return;rt.erase(brush,x,y);this.fogProgress=Math.min(100,this.fogProgress+1.25);if(this.fogProgress>42)this.complete()});this.feedback('别点击“完成”。用手把雾真正擦开。')}
  complete(){if(this.completed)return;this.completed=true;this.state.prologue.water=true;this.state.visitedShopCount=Math.min(7,(this.state.visitedShopCount||0)+1);bus.emit('observation','water_reverse');bus.emit('observation','mother_note');this.store.save();this.feedback('年轻的师父与母亲出现在镜后。她只写到：“不要替他——”。',true);this.time.delayedCall(this.state.reduced?400:1800,()=>{bus.emit('chapter2')})}
}
